- name: "type: feature"
  color: "3E4B9E"
  description: "New feature or enhancement"
- name: "type: bug"
  color: "D73A4A"
  description: "Fixes a defect or regression"
- name: "type: chore"
  color: "6ED28F"
  description: "Maintenance or refactor work"
- name: "type: docs"
  color: "1D76DB"
  description: "Documentation-only changes"
- name: "area: frontend"
  color: "F9A825"
  description: "Impacts web UI or Storybook"
- name: "area: backend"
  color: "795548"
  description: "Impacts API, server, or data layer"
- name: "area: infra"
  color: "0E8A16"
  description: "Infrastructure, CI/CD, or tooling changes"
- name: "priority: p0"
  color: "B60205"
  description: "Critical issue requiring immediate attention"
- name: "priority: p1"
  color: "EC6EB6"
  description: "High-priority work to schedule soon"
- name: "priority: p2"
  color: "5319E7"
  description: "Normal priority"
- name: "priority: p3"
  color: "BFDADC"
  description: "Nice-to-have or backlog"
