name: 機能要望
description: 改善案や新機能の提案に利用してください。
title: "[Feature] "
labels:
  - type: feature
  - priority: p2
body:
  - type: markdown
    attributes:
      value: |
        ## 機能要望テンプレート
        提案の背景や成果を明確にすると優先度判断がしやすくなります。
  - type: textarea
    id: problem
    attributes:
      label: 課題
      description: ユーザーやビジネス上の課題を記載してください。
      placeholder: どのようなペインやギャップがあるか
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 提案する解決策
      description: 想定しているアプローチ・UX・機能概要を記載してください。
      placeholder: 例) タスク一覧に〇〇フィルターを追加する
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 検討した代替案
      description: 他に検討した案があれば記載してください。
  - type: textarea
    id: impact
    attributes:
      label: 期待する効果
      description: KPI・ユーザー価値・運用負荷など、期待値を記載してください。
  - type: textarea
    id: acceptance
    attributes:
      label: 受け入れ条件
      description: 完了とみなすための条件をチェックリスト形式で記載してください。
      placeholder: |
        - [ ] 条件1
        - [ ] 条件2
  - type: textarea
    id: notes
    attributes:
      label: 補足情報
      description: 関連資料（デザイン、データ、参考リンク等）があれば添付してください。
